import json
import requests
from datetime import datetime
import pytz

# Major world cities with their timezone identifiers
cities = [
    # Asia
    {"name": "Tokyo", "timezone": "Asia/Tokyo", "country": "Japan"},
    {"name": "Delhi", "timezone": "Asia/Kolkata", "country": "India"},
    {"name": "Shanghai", "timezone": "Asia/Shanghai", "country": "China"},
    {"name": "Mumbai", "timezone": "Asia/Kolkata", "country": "India"},
    {"name": "Beijing", "timezone": "Asia/Shanghai", "country": "China"},
    {"name": "Osaka", "timezone": "Asia/Tokyo", "country": "Japan"},
    {"name": "Dhaka", "timezone": "Asia/Dhaka", "country": "Bangladesh"},
    {"name": "Karachi", "timezone": "Asia/Karachi", "country": "Pakistan"},
    {"name": "Chongqing", "timezone": "Asia/Shanghai", "country": "China"},
    {"name": "Istanbul", "timezone": "Europe/Istanbul", "country": "Turkey"},
    {"name": "Kolkata", "timezone": "Asia/Kolkata", "country": "India"},
    {"name": "Manila", "timezone": "Asia/Manila", "country": "Philippines"},
    {"name": "Tianjin", "timezone": "Asia/Shanghai", "country": "China"},
    {"name": "Guangzhou", "timezone": "Asia/Shanghai", "country": "China"},
    {"name": "Lahore", "timezone": "Asia/Karachi", "country": "Pakistan"},
    {"name": "Bangalore", "timezone": "Asia/Kolkata", "country": "India"},
    {"name": "Shenzhen", "timezone": "Asia/Shanghai", "country": "China"},
    {"name": "Seoul", "timezone": "Asia/Seoul", "country": "South Korea"},
    {"name": "Chennai", "timezone": "Asia/Kolkata", "country": "India"},
    {"name": "Jakarta", "timezone": "Asia/Jakarta", "country": "Indonesia"},
    {"name": "Bangkok", "timezone": "Asia/Bangkok", "country": "Thailand"},
    {"name": "Hyderabad", "timezone": "Asia/Kolkata", "country": "India"},
    {"name": "Ho Chi Minh City", "timezone": "Asia/Ho_Chi_Minh", "country": "Vietnam"},
    {"name": "Ahmedabad", "timezone": "Asia/Kolkata", "country": "India"},
    {"name": "Kuala Lumpur", "timezone": "Asia/Kuala_Lumpur", "country": "Malaysia"},
    {"name": "Wuhan", "timezone": "Asia/Shanghai", "country": "China"},
    {"name": "Xiamen", "timezone": "Asia/Shanghai", "country": "China"},
    {"name": "Surat", "timezone": "Asia/Kolkata", "country": "India"},
    {"name": "Nanjing", "timezone": "Asia/Shanghai", "country": "China"},
    {"name": "Pune", "timezone": "Asia/Kolkata", "country": "India"},
    {"name": "Hanoi", "timezone": "Asia/Ho_Chi_Minh", "country": "Vietnam"},
    {"name": "Singapore", "timezone": "Asia/Singapore", "country": "Singapore"},
    {"name": "Riyadh", "timezone": "Asia/Riyadh", "country": "Saudi Arabia"},
    {"name": "Yangon", "timezone": "Asia/Yangon", "country": "Myanmar"},
    {"name": "Shenyang", "timezone": "Asia/Shanghai", "country": "China"},
    {"name": "Bagdad", "timezone": "Asia/Baghdad", "country": "Iraq"},
    {"name": "Jeddah", "timezone": "Asia/Riyadh", "country": "Saudi Arabia"},
    {"name": "Dongguan", "timezone": "Asia/Shanghai", "country": "China"},
    {"name": "Foshan", "timezone": "Asia/Shanghai", "country": "China"},
    {"name": "Fukuoka", "timezone": "Asia/Tokyo", "country": "Japan"},
    {"name": "Jaipur", "timezone": "Asia/Kolkata", "country": "India"},
    {"name": "Suzhou", "timezone": "Asia/Shanghai", "country": "China"},
    {"name": "Kano", "timezone": "Africa/Lagos", "country": "Nigeria"},
    {"name": "Lucknow", "timezone": "Asia/Kolkata", "country": "India"},
    {"name": "Kanpur", "timezone": "Asia/Kolkata", "country": "India"},
    {"name": "Nagoya", "timezone": "Asia/Tokyo", "country": "Japan"},
    {"name": "Hefei", "timezone": "Asia/Shanghai", "country": "China"},
    {"name": "Mashhad", "timezone": "Asia/Tehran", "country": "Iran"},
    {"name": "Pyongyang", "timezone": "Asia/Pyongyang", "country": "North Korea"},
    
    # Europe
    {"name": "London", "timezone": "Europe/London", "country": "United Kingdom"},
    {"name": "Paris", "timezone": "Europe/Paris", "country": "France"},
    {"name": "Madrid", "timezone": "Europe/Madrid", "country": "Spain"},
    {"name": "Barcelona", "timezone": "Europe/Madrid", "country": "Spain"},
    {"name": "Rome", "timezone": "Europe/Rome", "country": "Italy"},
    {"name": "Berlin", "timezone": "Europe/Berlin", "country": "Germany"},
    {"name": "Milan", "timezone": "Europe/Rome", "country": "Italy"},
    {"name": "Naples", "timezone": "Europe/Rome", "country": "Italy"},
    {"name": "Hamburg", "timezone": "Europe/Berlin", "country": "Germany"},
    {"name": "Munich", "timezone": "Europe/Berlin", "country": "Germany"},
    {"name": "Warsaw", "timezone": "Europe/Warsaw", "country": "Poland"},
    {"name": "Budapest", "timezone": "Europe/Budapest", "country": "Hungary"},
    {"name": "Vienna", "timezone": "Europe/Vienna", "country": "Austria"},
    {"name": "Prague", "timezone": "Europe/Prague", "country": "Czech Republic"},
    {"name": "Brussels", "timezone": "Europe/Brussels", "country": "Belgium"},
    {"name": "Amsterdam", "timezone": "Europe/Amsterdam", "country": "Netherlands"},
    {"name": "Stockholm", "timezone": "Europe/Stockholm", "country": "Sweden"},
    {"name": "Copenhagen", "timezone": "Europe/Copenhagen", "country": "Denmark"},
    {"name": "Oslo", "timezone": "Europe/Oslo", "country": "Norway"},
    {"name": "Helsinki", "timezone": "Europe/Helsinki", "country": "Finland"},
    {"name": "Zurich", "timezone": "Europe/Zurich", "country": "Switzerland"},
    {"name": "Geneva", "timezone": "Europe/Zurich", "country": "Switzerland"},
    {"name": "Lisbon", "timezone": "Europe/Lisbon", "country": "Portugal"},
    {"name": "Athens", "timezone": "Europe/Athens", "country": "Greece"},
    {"name": "Bucharest", "timezone": "Europe/Bucharest", "country": "Romania"},
    {"name": "Sofia", "timezone": "Europe/Sofia", "country": "Bulgaria"},
    {"name": "Belgrade", "timezone": "Europe/Belgrade", "country": "Serbia"},
    {"name": "Zagreb", "timezone": "Europe/Zagreb", "country": "Croatia"},
    {"name": "Ljubljana", "timezone": "Europe/Ljubljana", "country": "Slovenia"},
    {"name": "Bratislava", "timezone": "Europe/Bratislava", "country": "Slovakia"},
    {"name": "Tallinn", "timezone": "Europe/Tallinn", "country": "Estonia"},
    {"name": "Riga", "timezone": "Europe/Riga", "country": "Latvia"},
    {"name": "Vilnius", "timezone": "Europe/Vilnius", "country": "Lithuania"},
    {"name": "Kiev", "timezone": "Europe/Kiev", "country": "Ukraine"},
    {"name": "Minsk", "timezone": "Europe/Minsk", "country": "Belarus"},
    {"name": "Moscow", "timezone": "Europe/Moscow", "country": "Russia"},
    {"name": "Saint Petersburg", "timezone": "Europe/Moscow", "country": "Russia"},
    
    # North America
    {"name": "New York", "timezone": "America/New_York", "country": "United States"},
    {"name": "Los Angeles", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Chicago", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Houston", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Phoenix", "timezone": "America/Phoenix", "country": "United States"},
    {"name": "Philadelphia", "timezone": "America/New_York", "country": "United States"},
    {"name": "San Antonio", "timezone": "America/Chicago", "country": "United States"},
    {"name": "San Diego", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Dallas", "timezone": "America/Chicago", "country": "United States"},
    {"name": "San Jose", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Austin", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Jacksonville", "timezone": "America/New_York", "country": "United States"},
    {"name": "Fort Worth", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Columbus", "timezone": "America/New_York", "country": "United States"},
    {"name": "Charlotte", "timezone": "America/New_York", "country": "United States"},
    {"name": "San Francisco", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Indianapolis", "timezone": "America/Indiana/Indianapolis", "country": "United States"},
    {"name": "Seattle", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Denver", "timezone": "America/Denver", "country": "United States"},
    {"name": "Washington", "timezone": "America/New_York", "country": "United States"},
    {"name": "Boston", "timezone": "America/New_York", "country": "United States"},
    {"name": "El Paso", "timezone": "America/Denver", "country": "United States"},
    {"name": "Nashville", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Detroit", "timezone": "America/Detroit", "country": "United States"},
    {"name": "Oklahoma City", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Portland", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Las Vegas", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Memphis", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Louisville", "timezone": "America/Kentucky/Louisville", "country": "United States"},
    {"name": "Baltimore", "timezone": "America/New_York", "country": "United States"},
    {"name": "Milwaukee", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Albuquerque", "timezone": "America/Denver", "country": "United States"},
    {"name": "Tucson", "timezone": "America/Phoenix", "country": "United States"},
    {"name": "Fresno", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Sacramento", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Kansas City", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Mesa", "timezone": "America/Phoenix", "country": "United States"},
    {"name": "Atlanta", "timezone": "America/New_York", "country": "United States"},
    {"name": "Omaha", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Colorado Springs", "timezone": "America/Denver", "country": "United States"},
    {"name": "Raleigh", "timezone": "America/New_York", "country": "United States"},
    {"name": "Miami", "timezone": "America/New_York", "country": "United States"},
    {"name": "Virginia Beach", "timezone": "America/New_York", "country": "United States"},
    {"name": "Oakland", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Minneapolis", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Tulsa", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Arlington", "timezone": "America/Chicago", "country": "United States"},
    {"name": "New Orleans", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Wichita", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Cleveland", "timezone": "America/New_York", "country": "United States"},
    {"name": "Tampa", "timezone": "America/New_York", "country": "United States"},
    {"name": "Bakersfield", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Aurora", "timezone": "America/Denver", "country": "United States"},
    {"name": "Honolulu", "timezone": "Pacific/Honolulu", "country": "United States"},
    {"name": "Anaheim", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Santa Ana", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Corpus Christi", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Riverside", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Lexington", "timezone": "America/Kentucky/Louisville", "country": "United States"},
    {"name": "Stockton", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Henderson", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Saint Paul", "timezone": "America/Chicago", "country": "United States"},
    {"name": "St. Louis", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Cincinnati", "timezone": "America/New_York", "country": "United States"},
    {"name": "Pittsburgh", "timezone": "America/New_York", "country": "United States"},
    {"name": "Greensboro", "timezone": "America/New_York", "country": "United States"},
    {"name": "Anchorage", "timezone": "America/Anchorage", "country": "United States"},
    {"name": "Plano", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Lincoln", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Orlando", "timezone": "America/New_York", "country": "United States"},
    {"name": "Irvine", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Newark", "timezone": "America/New_York", "country": "United States"},
    {"name": "Durham", "timezone": "America/New_York", "country": "United States"},
    {"name": "Chula Vista", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Toledo", "timezone": "America/New_York", "country": "United States"},
    {"name": "Fort Wayne", "timezone": "America/Indiana/Indianapolis", "country": "United States"},
    {"name": "St. Petersburg", "timezone": "America/New_York", "country": "United States"},
    {"name": "Laredo", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Jersey City", "timezone": "America/New_York", "country": "United States"},
    {"name": "Chandler", "timezone": "America/Phoenix", "country": "United States"},
    {"name": "Madison", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Lubbock", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Norfolk", "timezone": "America/New_York", "country": "United States"},
    {"name": "Baton Rouge", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Buffalo", "timezone": "America/New_York", "country": "United States"},
    {"name": "North Las Vegas", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Gilbert", "timezone": "America/Phoenix", "country": "United States"},
    {"name": "Glendale", "timezone": "America/Phoenix", "country": "United States"},
    {"name": "Reno", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Hialeah", "timezone": "America/New_York", "country": "United States"},
    {"name": "Garland", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Chesapeake", "timezone": "America/New_York", "country": "United States"},
    {"name": "Irving", "timezone": "America/Chicago", "country": "United States"},
    {"name": "North Hempstead", "timezone": "America/New_York", "country": "United States"},
    {"name": "Scottsdale", "timezone": "America/Phoenix", "country": "United States"},
    {"name": "Boise", "timezone": "America/Boise", "country": "United States"},
    {"name": "Fremont", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Richmond", "timezone": "America/New_York", "country": "United States"},
    {"name": "San Bernardino", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Birmingham", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Spokane", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Rochester", "timezone": "America/New_York", "country": "United States"},
    {"name": "Des Moines", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Modesto", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Fayetteville", "timezone": "America/New_York", "country": "United States"},
    {"name": "Tacoma", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Oxnard", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Fontana", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Columbus", "timezone": "America/New_York", "country": "United States"},
    {"name": "Montgomery", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Moreno Valley", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Shreveport", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Aurora", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Yonkers", "timezone": "America/New_York", "country": "United States"},
    {"name": "Akron", "timezone": "America/New_York", "country": "United States"},
    {"name": "Huntington Beach", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Little Rock", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Augusta", "timezone": "America/New_York", "country": "United States"},
    {"name": "Amarillo", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Glendale", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Mobile", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Grand Rapids", "timezone": "America/Detroit", "country": "United States"},
    {"name": "Salt Lake City", "timezone": "America/Denver", "country": "United States"},
    {"name": "Tallahassee", "timezone": "America/New_York", "country": "United States"},
    {"name": "Huntsville", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Grand Prairie", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Knoxville", "timezone": "America/New_York", "country": "United States"},
    {"name": "Worcester", "timezone": "America/New_York", "country": "United States"},
    {"name": "Newport News", "timezone": "America/New_York", "country": "United States"},
    {"name": "Brownsville", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Overland Park", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Santa Clarita", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Providence", "timezone": "America/New_York", "country": "United States"},
    {"name": "Garden Grove", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Chattanooga", "timezone": "America/New_York", "country": "United States"},
    {"name": "Oceanside", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Jackson", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Fort Lauderdale", "timezone": "America/New_York", "country": "United States"},
    {"name": "Santa Rosa", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Rancho Cucamonga", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Port St. Lucie", "timezone": "America/New_York", "country": "United States"},
    {"name": "Tempe", "timezone": "America/Phoenix", "country": "United States"},
    {"name": "Ontario", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Vancouver", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Cape Coral", "timezone": "America/New_York", "country": "United States"},
    {"name": "Sioux Falls", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Springfield", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Peoria", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Pembroke Pines", "timezone": "America/New_York", "country": "United States"},
    {"name": "Elk Grove", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Salem", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Lancaster", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Corona", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Eugene", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Palmdale", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Salinas", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Springfield", "timezone": "America/New_York", "country": "United States"},
    {"name": "Pasadena", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Fort Collins", "timezone": "America/Denver", "country": "United States"},
    {"name": "Hayward", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Pomona", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Cary", "timezone": "America/New_York", "country": "United States"},
    {"name": "Rockford", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Alexandria", "timezone": "America/New_York", "country": "United States"},
    {"name": "Escondido", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "McKinney", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Kansas City", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Joliet", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Sunnyvale", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Torrance", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Bridgeport", "timezone": "America/New_York", "country": "United States"},
    {"name": "Lakewood", "timezone": "America/Denver", "country": "United States"},
    {"name": "Hollywood", "timezone": "America/New_York", "country": "United States"},
    {"name": "Paterson", "timezone": "America/New_York", "country": "United States"},
    {"name": "Naperville", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Syracuse", "timezone": "America/New_York", "country": "United States"},
    {"name": "Mesquite", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Dayton", "timezone": "America/New_York", "country": "United States"},
    {"name": "Savannah", "timezone": "America/New_York", "country": "United States"},
    {"name": "Clarksville", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Orange", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Pasadena", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Fullerton", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Killeen", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Frisco", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Hampton", "timezone": "America/New_York", "country": "United States"},
    {"name": "McAllen", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Warren", "timezone": "America/Detroit", "country": "United States"},
    {"name": "Bellevue", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "West Valley City", "timezone": "America/Denver", "country": "United States"},
    {"name": "Columbia", "timezone": "America/New_York", "country": "United States"},
    {"name": "Olathe", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Sterling Heights", "timezone": "America/Detroit", "country": "United States"},
    {"name": "New Haven", "timezone": "America/New_York", "country": "United States"},
    {"name": "Miramar", "timezone": "America/New_York", "country": "United States"},
    {"name": "Waco", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Thousand Oaks", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Cedar Rapids", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Charleston", "timezone": "America/New_York", "country": "United States"},
    {"name": "Visalia", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Topeka", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Elizabeth", "timezone": "America/New_York", "country": "United States"},
    {"name": "Gainesville", "timezone": "America/New_York", "country": "United States"},
    {"name": "Thornton", "timezone": "America/Denver", "country": "United States"},
    {"name": "Roseville", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Carrollton", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Coral Springs", "timezone": "America/New_York", "country": "United States"},
    {"name": "Stamford", "timezone": "America/New_York", "country": "United States"},
    {"name": "Simi Valley", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Concord", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Hartford", "timezone": "America/New_York", "country": "United States"},
    {"name": "Kent", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Lafayette", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Midland", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Surprise", "timezone": "America/Phoenix", "country": "United States"},
    {"name": "Denton", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Victorville", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Evansville", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Santa Clara", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Abilene", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Athens", "timezone": "America/New_York", "country": "United States"},
    {"name": "Vallejo", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Allentown", "timezone": "America/New_York", "country": "United States"},
    {"name": "Norman", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Beaumont", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Independence", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Murfreesboro", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Ann Arbor", "timezone": "America/Detroit", "country": "United States"},
    {"name": "Springfield", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Berkeley", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Peoria", "timezone": "America/Phoenix", "country": "United States"},
    {"name": "Provo", "timezone": "America/Denver", "country": "United States"},
    {"name": "El Monte", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Columbia", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Lansing", "timezone": "America/Detroit", "country": "United States"},
    {"name": "Fargo", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Downey", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Costa Mesa", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Wilmington", "timezone": "America/New_York", "country": "United States"},
    {"name": "Arvada", "timezone": "America/Denver", "country": "United States"},
    {"name": "Inglewood", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Miami Gardens", "timezone": "America/New_York", "country": "United States"},
    {"name": "Carlsbad", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Westminster", "timezone": "America/Denver", "country": "United States"},
    {"name": "Rochester", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Odessa", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Manchester", "timezone": "America/New_York", "country": "United States"},
    {"name": "Elgin", "timezone": "America/Chicago", "country": "United States"},
    {"name": "West Jordan", "timezone": "America/Denver", "country": "United States"},
    {"name": "Round Rock", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Clearwater", "timezone": "America/New_York", "country": "United States"},
    {"name": "Waterbury", "timezone": "America/New_York", "country": "United States"},
    {"name": "Gresham", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Fairfield", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Billings", "timezone": "America/Denver", "country": "United States"},
    {"name": "Lowell", "timezone": "America/New_York", "country": "United States"},
    {"name": "San Buenaventura", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Richardson", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Pueblo", "timezone": "America/Denver", "country": "United States"},
    {"name": "High Point", "timezone": "America/New_York", "country": "United States"},
    {"name": "West Covina", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Richmond", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Murrieta", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Pompano Beach", "timezone": "America/New_York", "country": "United States"},
    {"name": "Daly City", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Temecula", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Miami Beach", "timezone": "America/New_York", "country": "United States"},
    {"name": "Burbank", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "South Bend", "timezone": "America/Indiana/Indianapolis", "country": "United States"},
    {"name": "Lakeland", "timezone": "America/New_York", "country": "United States"},
    {"name": "Spokane", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Rialto", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Knoxville", "timezone": "America/New_York", "country": "United States"},
    {"name": "Davenport", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Yakima", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Las Cruces", "timezone": "America/Denver", "country": "United States"},
    {"name": "Samford", "timezone": "America/New_York", "country": "United States"},
    {"name": "Carmel", "timezone": "America/Indiana/Indianapolis", "country": "United States"},
    {"name": "Albany", "timezone": "America/New_York", "country": "United States"},
    {"name": "Chico", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Renton", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "South Gate", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Menifee", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Flint", "timezone": "America/Detroit", "country": "United States"},
    {"name": "Wichita Falls", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Green Bay", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Citrus Heights", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Longview", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Bloomington", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Lawton", "timezone": "America/Chicago", "country": "United States"},
    {"name": "San Mateo", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Lewisville", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Fishers", "timezone": "America/Indiana/Indianapolis", "country": "United States"},
    {"name": "Tuscaloosa", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Pearland", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Redding", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Danbury", "timezone": "America/New_York", "country": "United States"},
    {"name": "Bellingham", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Champaign", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Clifton", "timezone": "America/New_York", "country": "United States"},
    {"name": "Alhambra", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Evanston", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Livermore", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Westland", "timezone": "America/Detroit", "country": "United States"},
    {"name": "Norwalk", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Boynton Beach", "timezone": "America/New_York", "country": "United States"},
    {"name": "Waukegan", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Tyler", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Rapid City", "timezone": "America/Denver", "country": "United States"},
    {"name": "Layton", "timezone": "America/Denver", "country": "United States"},
    {"name": "Whittier", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Hawthorne", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Vacaville", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Galveston", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Appleton", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Gastonia", "timezone": "America/New_York", "country": "United States"},
    {"name": "Warwick", "timezone": "America/New_York", "country": "United States"},
    {"name": "Huber Heights", "timezone": "America/New_York", "country": "United States"},
    {"name": "Roanoke", "timezone": "America/New_York", "country": "United States"},
    {"name": "Hillsboro", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Bend", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Lakewood", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Merced", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Mission Viejo", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Chino", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Redwood City", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Edinburg", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Cranston", "timezone": "America/New_York", "country": "United States"},
    {"name": "Parma", "timezone": "America/New_York", "country": "United States"},
    {"name": "New Rochelle", "timezone": "America/New_York", "country": "United States"},
    {"name": "Lake Forest", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Napa", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Hammond", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Fayetteville", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Bloomington", "timezone": "America/Indiana/Indianapolis", "country": "United States"},
    {"name": "Avondale", "timezone": "America/Phoenix", "country": "United States"},
    {"name": "Somerville", "timezone": "America/New_York", "country": "United States"},
    {"name": "Palm Bay", "timezone": "America/New_York", "country": "United States"},
    {"name": "Bryan", "timezone": "America/Chicago", "country": "United States"},
    {"name": "San Leandro", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Nashua", "timezone": "America/New_York", "country": "United States"},
    {"name": "Plantation", "timezone": "America/New_York", "country": "United States"},
    {"name": "North Charleston", "timezone": "America/New_York", "country": "United States"},
    {"name": "Brockton", "timezone": "America/New_York", "country": "United States"},
    {"name": "Renton", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Spokane Valley", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Lorain", "timezone": "America/New_York", "country": "United States"},
    {"name": "Garland", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Palo Alto", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Royal Oak", "timezone": "America/Detroit", "country": "United States"},
    {"name": "Des Plaines", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Turlock", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Southfield", "timezone": "America/Detroit", "country": "United States"},
    {"name": "Lynchburg", "timezone": "America/New_York", "country": "United States"},
    {"name": "Ventura", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Decatur", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Missoula", "timezone": "America/Denver", "country": "United States"},
    {"name": "Minot", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Asheville", "timezone": "America/New_York", "country": "United States"},
    {"name": "Hoboken", "timezone": "America/New_York", "country": "United States"},
    {"name": "Delray Beach", "timezone": "America/New_York", "country": "United States"},
    {"name": "Diamond Bar", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Woodland", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Valdosta", "timezone": "America/New_York", "country": "United States"},
    {"name": "Clifton", "timezone": "America/New_York", "country": "United States"},
    {"name": "Huntington Park", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Gulfport", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Alafaya", "timezone": "America/New_York", "country": "United States"},
    {"name": "Bethlehem", "timezone": "America/New_York", "country": "United States"},
    {"name": "Cheektowaga", "timezone": "America/New_York", "country": "United States"},
    {"name": "Daytona Beach", "timezone": "America/New_York", "country": "United States"},
    {"name": "Alpharetta", "timezone": "America/New_York", "country": "United States"},
    {"name": "Wellington", "timezone": "America/New_York", "country": "United States"},
    {"name": "Dundalk", "timezone": "America/New_York", "country": "United States"},
    {"name": "Germantown", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Yorba Linda", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "San Clemente", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Laguna Niguel", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Cerritos", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Bellflower", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Hemet", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Beaverton", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Menifee", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Springdale", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Concord", "timezone": "America/New_York", "country": "United States"},
    {"name": "Milpitas", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Addison", "timezone": "America/Chicago", "country": "United States"},
    {"name": "West Allis", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Margate", "timezone": "America/New_York", "country": "United States"},
    {"name": "Baytown", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Placentia", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Greenville", "timezone": "America/New_York", "country": "United States"},
    {"name": "Cleveland Heights", "timezone": "America/New_York", "country": "United States"},
    {"name": "Bartlett", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Tulare", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Lakewood", "timezone": "America/New_York", "country": "United States"},
    {"name": "Euclid", "timezone": "America/New_York", "country": "United States"},
    {"name": "Coconut Creek", "timezone": "America/New_York", "country": "United States"},
    {"name": "Petaluma", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Kissimmee", "timezone": "America/New_York", "country": "United States"},
    {"name": "Homestead", "timezone": "America/New_York", "country": "United States"},
    {"name": "Camarillo", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Troy", "timezone": "America/Detroit", "country": "United States"},
    {"name": "Johns Creek", "timezone": "America/New_York", "country": "United States"},
    {"name": "Dearborn Heights", "timezone": "America/Detroit", "country": "United States"},
    {"name": "Eagan", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Roswell", "timezone": "America/New_York", "country": "United States"},
    {"name": "Chow Chow", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Maple Grove", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Brookhaven", "timezone": "America/New_York", "country": "United States"},
    {"name": "Huntington", "timezone": "America/New_York", "country": "United States"},
    {"name": "Pawtucket", "timezone": "America/New_York", "country": "United States"},
    {"name": "Bolingbrook", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Pharr", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Schaumburg", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Southaven", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Rogers", "timezone": "America/Chicago", "country": "United States"},
    {"name": "St. George", "timezone": "America/Denver", "country": "United States"},
    {"name": "Hoover", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Sunrise", "timezone": "America/New_York", "country": "United States"},
    {"name": "Rosemead", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Bowling Green", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Corvallis", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Dearborn", "timezone": "America/Detroit", "country": "United States"},
    {"name": "Wausau", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Joplin", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Bismarck", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Kennewick", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Panama City", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Fitchburg", "timezone": "America/New_York", "country": "United States"},
    {"name": "Sheboygan", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Jeffersonville", "timezone": "America/Kentucky/Louisville", "country": "United States"},
    {"name": "Noblesville", "timezone": "America/Indiana/Indianapolis", "country": "United States"},
    {"name": "Roseville", "timezone": "America/Detroit", "country": "United States"},
    {"name": "Hanford", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Paramount", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Oakley", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Kettering", "timezone": "America/New_York", "country": "United States"},
    {"name": "Largo", "timezone": "America/New_York", "country": "United States"},
    {"name": "Middletown", "timezone": "America/New_York", "country": "United States"},
    {"name": "Riverside", "timezone": "America/New_York", "country": "United States"},
    {"name": "Newark", "timezone": "America/New_York", "country": "United States"},
    {"name": "Surprise", "timezone": "America/Phoenix", "country": "United States"},
    {"name": "Celina", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Edinburg", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Mentor", "timezone": "America/New_York", "country": "United States"},
    {"name": "Kirkland", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Chicopee", "timezone": "America/New_York", "country": "United States"},
    {"name": "Charleston", "timezone": "America/New_York", "country": "United States"},
    {"name": "Medford", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Cicero", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Carrollton", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Westminster", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Clovis", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Meridian", "timezone": "America/Boise", "country": "United States"},
    {"name": "Warwick", "timezone": "America/New_York", "country": "United States"},
    {"name": "Champaign", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Draper", "timezone": "America/Denver", "country": "United States"},
    {"name": "Miamisburg", "timezone": "America/New_York", "country": "United States"},
    {"name": "Parker", "timezone": "America/Denver", "country": "United States"},
    {"name": "Jülich", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Lima", "timezone": "America/New_York", "country": "United States"},
    {"name": "Yakima", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "St. Cloud", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Littleton", "timezone": "America/Denver", "country": "United States"},
    {"name": "Kenosha", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Edmond", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Downers Grove", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Hesperia", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Pompano Beach", "timezone": "America/New_York", "country": "United States"},
    {"name": "Biloxi", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Pueblo", "timezone": "America/Denver", "country": "United States"},
    {"name": "Carmel", "timezone": "America/New_York", "country": "United States"},
    {"name": "Sanford", "timezone": "America/New_York", "country": "United States"},
    {"name": "Moorhead", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Ames", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Malden", "timezone": "America/New_York", "country": "United States"},
    {"name": "Mckinney", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Bartlesville", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Kalamazoo", "timezone": "America/Detroit", "country": "United States"},
    {"name": "Rockville", "timezone": "America/New_York", "country": "United States"},
    {"name": "Taunton", "timezone": "America/New_York", "country": "United States"},
    {"name": "New London", "timezone": "America/New_York", "country": "United States"},
    {"name": "Kenner", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Fort Myers", "timezone": "America/New_York", "country": "United States"},
    {"name": "Frederick", "timezone": "America/New_York", "country": "United States"},
    {"name": "Daly City", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Morgan Hill", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Edmonds", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Burien", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Burnsville", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Lacey", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Kearny", "timezone": "America/New_York", "country": "United States"},
    {"name": "Endwell", "timezone": "America/New_York", "country": "United States"},
    {"name": "Greenwood", "timezone": "America/Indiana/Indianapolis", "country": "United States"},
    {"name": "Brooklyn Park", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Richfield", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Lynwood", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Lakewood", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Meriden", "timezone": "America/New_York", "country": "United States"},
    {"name": "Pampa", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Sammamish", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Northglenn", "timezone": "America/Denver", "country": "United States"},
    {"name": "Prescott", "timezone": "America/Phoenix", "country": "United States"},
    {"name": "Utica", "timezone": "America/New_York", "country": "United States"},
    {"name": "St. Peters", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Clearfield", "timezone": "America/Denver", "country": "United States"},
    {"name": "Union City", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Marlborough", "timezone": "America/New_York", "country": "United States"},
    {"name": "Duluth", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Redlands", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Jackson", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Danville", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Taylorsville", "timezone": "America/Denver", "country": "United States"},
    {"name": "Moline", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Yuma", "timezone": "America/Phoenix", "country": "United States"},
    {"name": "Yorba Linda", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Auburn", "timezone": "America/Los_Angeles", "country": "United States"},
    {"name": "Decatur", "timezone": "America/New_York", "country": "United States"},
    {"name": "Dothan", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Huntsville", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Cedar Falls", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Flagstaff", "timezone": "America/Phoenix", "country": "United States"},
    {"name": "Lynchburg", "timezone": "America/New_York", "country": "United States"},
    {"name": "Waterloo", "timezone": "America/Chicago", "country": "United States"},
    {"name": "Wylie", "timezone": "America/Chicago", "country": "United States"}
]

# Write the data to timezones.json
with open('timezones.json', 'w', encoding='utf-8') as f:
    json.dump(cities, f, indent=2, ensure_ascii=False)

print(f"Generated timezones.json with {len(cities)} cities")